language: java

jdk:
  - openjdk11

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew -x test build --parallel"

############################ 배포 필요할 때 풀 것
#before_deploy:
#  - mkdir -p before-deploy
#  - cp scripts/*.sh before-deploy/
#  - cp appspec.yml before-deploy/
#  - cp module-api/build/libs/*.jar before-deploy/
#  - cd before-deploy && zip -r before-deploy *
#  - cd ../ && mkdir -p deploy
#  - mv before-deploy/before-deploy.zip deploy/woomool-market.zip
#
#deploy:
#  - provider: s3
#    local_dir: deploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: woomool-market
#    region: ap-northeast-2
#    acl: private
#    wait_until_deployed: true
#    skip_cleanup: true
#    on:
#      repo: Ryu-JeongMoon/woomool-market
#      branch: develop
#
#  - provider: codedeploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: woomool-market
#    key: woomool-market.zip
#    bundle_type: zip
#    application: woomool-market
#    deployment_group: woomool-market-group
#    region: ap-northeast-2
#    wait_until_deployed: true
#    on:
#      repo: Ryu-JeongMoon/woomool-market
#      branch: develop

notifications:
  slack:
    secure: Yxyqny5z3i4ltdljZMTp+yQLJ928O3r+OVRQAk0P1AOr5Lzu+aEqv+4YJdo5FoTIImF0XeIw8X/fyujKueqdq6BCtKkXja1L1wTDVuPIMWQJv+47eC0eqGhNs8ids5ePuH3LDL0vARu795s2E3xCG3dZDu7a0yXWNDJYT+C0NxEZW5wR+JLMVILXWsd28biM5njWiCOmvixRWyw3u7vVQn1a5TbmOt0NSu1N2c1J53kzFyj1dbntNc+C3eUJc3l6AdpsjJLzH2mC26UzwGXuu5sUrILFp8sECRlmUB1Vk4/8Ed3aGbRzmmdmaZ8QdEBgeT3sJ+bdAteC3prln/B/nF2GNR6FAYk1WS+k6SXcED0TwMqKq7NZIy92EZQCi0U1dxvymqsng4xXZ+3V7e0rseCh1YZnP8pDQ1OT6jrv3QuJgm/W+7SZI0maeSonMSZxxc0knZScaTRAtu2sNowvqfW64D5yq+Ty9BI1vb5wq4epkDsIE2ZTpcNolmtWPZOb7sc3Pcp9AKji1otwSDruRZ9sOdgRi2MxH5xGELYaoosFUdHYzTHe7uXBf8z92zMhGTQlLOMO5u5nAVewT3NsK25VMa7YNwql0+MxZ/O3P9572vZMIPL5pwzEZ6Lnkxvfse0Q317akXnYEqInf4sSQfrOudwa1L1NCOm1W5R24jg=
