language: java

jdk:
  - openjdk11

branches:
  only:
    - woomool-market-135
#    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew -x test build --parallel"

before_deploy:
  - zip -r woomool-market *
  - mkdir -p deploy
  - mv woomool-market.zip deploy/woomool-market.zip

deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: woomool-market
    region: ap-northeast-2
    acl: public_read
    wait_until_deployed: true
    on:
      repo: Ryu-JeongMoon/woomool-market
      branch: woomool-market-135

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: woomool-market
    key: woomool-market.zip
    bundle_type: zip
    application: woomool-market
    deployment_group: woomool-market-group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      repo: Ryu-JeongMoon/woomool-market
      branch: woomool-market-135

notifications:
  slack: woomoolhq:4dinJbih6JoxnjuyIy9LqQxP
