language: java

jdk:
  - openjdk11

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew -x test build --parallel"

notifications:
  slack: woomoolhq:4dinJbih6JoxnjuyIy9LqQxP