version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/nonstop/module-api/
    overwrite : yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: execute-deploy.sh
      timeout: 180
      runas: ec2-user