package com.woomoolmarket.domain.enumeration;

public enum Region {
  GYEONGGIDO,
  GANGWONDO,
  CHUNGCHEONGBUKDO,
  CHUNGCHEONGNAMDO,
  GYEONGSANGBUKDO,
  GYEONGSANGNAMDO,
  JEOLLABUKDO,
  JEOLLANAMDO,
  JEJUDO
}
