### FIND ONE
GET https://localhost:8443/api/members/1
Content-Type: application/json

### ADMIN FIND ALL
GET https://localhost:8443/api/members/admin-only/all
Content-Type: application/json

### FIND ALL
GET https://localhost:8443/api/members

### XSS TEST
GET https://localhost:8443/xss

### LOGIN
POST https://localhost:8443/api/auth/login
Content-Type: application/json

{
  "email": "panda123456@gmail.com",
  "password": "1234"
}

### SIGNUP
POST https://localhost:8443/api/members
Content-Type: application/json

{
  "email": "panda123456@gmail.com",
  "userId": "pandabear",
  "nickname": "pandagom",
  "password": "1234",
  "address": {
    "city": "seoul",
    "street": "yeonhui-ro",
    "zipcode": "13392"
  }
}