GET https://localhost:8443/api/members/1
Content-Type: application/json

###
# Send API call
GET https://localhost:8443/api/members
Content-Type: application/json

###
GET https://localhost:8443/api/members

###
GET https://localhost:8443/xss